# Site Settings
title: Diamond Minding
email: web@diamondminding.uk
description: "Diamond Minding is a Brain Wave Balancing company from Reading, United Kingdom"
baseurl: ""
url: "http://diamondminding.uk"
author: "Mary Pearson"

# Main Navigation (Manual)
navigation:
 - text: Home
   url: /
 - text: About
   url: /about/
 - text: Services
   url: /services/
 - text: FAQ
   url: /faq/
 - text: Research
   url: /research/
 - text: Blog
   url: /blog/
 - text: Affiliates
   url: /affiliates/
 - text: Contact
   url: /contact/


# Build Settings
paginate: 3
paginate_path: "blog/page:num"
markdown: kramdown
permalink: pretty
